Updated for the case of no battle tag for a player
barrett777/Heroes.ReplayParser pull request #93
Opened 2020-01-22 00:48 UTC by koliva8245

[Cursed Hollow_NoBattleTag.zip](https://github.com/barrett777/Heroes.ReplayParser/files/4094640/Cursed.Hollow_NoBattleTag.zip)

This updates the full battlelobby parsing to account for player's with no battletag, however the other simple methods to obtains only the battletag do not work.

`GetBattleTags()` will get random digits for the number tag of the no-name player.  
`StandaloneBattleLobbyParser.Parse()` will get x-1 players.

No idea how to want to fix these, but you could always look the TID and work from there I guess.

2020-01-22 01:21 UTC, barrett777 requested changes
Thanks for looking into this!

2020-01-22 01:21 UTC, barrett777 commented on Heroes.ReplayParser/Player.cs
> +        public int? BattleTag { get; set; } = null;
I'd rather not change this to nullable.  I think it's fine to just be '0' in this extremely rare scenario.
```suggestion
        public int BattleTag { get; set; }
```

2020-01-22 01:53 UTC, barrett777 approved these changes

2020-01-22 01:53 UTC, merged

2020-01-23 13:12 UTC, Zemill commented
What does the return look like when there is no battletag?

2020-01-23 15:38 UTC, koliva8245 commented
Return of what? It's an empty string.